Repository re-cinq/aether, pull requests merged in 2024-04, with the labels that each got.

#67 feat: creates a plugin system
  .gitignore
  cmd/exporter/main.go
  docker-compose.yaml
  go.mod
  go.sum
  pkg/config/config.go
  pkg/config/types.go
  pkg/plugin/README.md
  pkg/plugin/buf.gen.yaml
  pkg/plugin/buf.yaml
  pkg/plugin/example/example.go
  pkg/plugin/exporter.go
  pkg/plugin/proto/converter.go
  pkg/plugin/proto/converter_test.go
  pkg/plugin/proto/plugin.pb.go
  pkg/plugin/proto/plugin.proto
  pkg/plugin/proto/plugin_grpc.pb.go
  pkg/plugin/subscriber.go
Labels: enhancement

#79 Contributing guide
  .github/workflows/conventional-commits.yaml
  README.md
  docs/CONTRIBUTING.md
  docs/DEVELOPMENT.md
  local.example.yaml
  pkg/config/config.go
Labels: documentation

#88 chore: add unique id as field in instance
  .gitignore
  pkg/plugin/proto/converter.go
  pkg/plugin/proto/converter_test.go
  pkg/plugin/proto/plugin.pb.go
  pkg/plugin/proto/plugin.proto
  pkg/providers/aws/ec2.go
  pkg/providers/gcp/gcp.go
  pkg/types/v1/instance.go
Labels: enhancement

#94 feat: create a source interface and manager
  pkg/source/interface.go
  pkg/source/manager.go
Labels: enhancement

#96 feat: change google provider to source
  cmd/exporter/main.go
  pkg/providers/gcp/scraper.go
  pkg/providers/gcp/source.go
  pkg/scraper/manager.go
  pkg/source/builtin.go
  pkg/source/manager.go
  pkg/types/v1/source.go
Labels: enhancement, gcp

#101 feat: change AWS provider to use source
  cmd/exporter/main.go
  pkg/providers/aws/aws.go
  pkg/providers/aws/scraper.go
  pkg/providers/aws/source.go
  pkg/scraper/manager.go
  pkg/source/builtin.go
Labels: enhancement, aws

#100 chore: add instance status
  pkg/calculator/handler.go
  pkg/exporter/handler.go
  pkg/plugin/proto/converter.go
  pkg/plugin/proto/converter_test.go
  pkg/plugin/proto/plugin.pb.go
  pkg/plugin/proto/plugin.proto
  pkg/providers/gcp/gcp.go
  pkg/providers/gcp/source.go
  pkg/types/v1/instance.go
Labels: enhancement

#105 fix: check for not exists error
  pkg/plugin/exporter.go
  pkg/plugin/source.go
Labels: bug

#106 chore: adds documentation website
  CONTRIBUTING.md
  DEVELOPMENT.md
  docs/.gitignore
  docs/README.md
  docs/babel.config.js
  docs/docs/config.md
  docs/docs/intro.md
  docs/docs/methodologies/_category_.json
  docs/docs/methodologies/methodologies.md
  docs/docs/sources/_category_.json
  docs/docs/sources/sources.md
  docs/docs/tutorials/_category_.json
  docs/docs/tutorials/getting-started.md
  docs/docusaurus.config.ts
  docs/package-lock.json
  docs/package.json
  docs/sidebars.ts
  docs/src/components/HomepageFeatures/index.tsx
  docs/src/components/HomepageFeatures/styles.module.css
  docs/src/css/custom.css
  docs/src/pages/index.module.css
  docs/src/pages/index.tsx
  docs/src/pages/markdown-page.md
  docs/static/.nojekyll
  docs/static/architecture.excalidraw
  docs/static/img/Byte-Calculating.webp
  docs/static/img/architecture.png
  docs/static/img/comparison_interpolations.webp
  docs/static/img/docusaurus-social-card.jpg
  docs/static/img/docusaurus.png
  docs/static/img/favicon.ico
  docs/static/img/linear_vs_proportionality.webp
  docs/static/img/logo.svg
  docs/static/img/undraw_docusaurus_mountain.svg
  docs/static/img/undraw_docusaurus_react.svg
  docs/static/img/undraw_docusaurus_tree.svg
  docs/tsconfig.json
Labels: documentation

#108 fix: broken doc links
  docs/docs/methodologies/methodologies.md
  docs/docs/tutorials/getting-started.md
Labels: bug, documentation

#112 feat: adds helm chart for easy deployment
  .github/workflows/helm.yaml
  .gitignore
  chart/aether/.helmignore
  chart/aether/Chart.yaml
  chart/aether/templates/NOTES.txt
  chart/aether/templates/_helpers.tpl
  chart/aether/templates/configmap.yaml
  chart/aether/templates/deployment.yaml
  chart/aether/templates/ingress.yaml
  chart/aether/templates/service.yaml
  chart/aether/templates/serviceaccount.yaml
  chart/aether/values.yaml
Labels: helm

#113 fix: helm release action
  .github/workflows/helm.yaml
  charts/aether/.helmignore
  charts/aether/Chart.yaml
  charts/aether/templates/NOTES.txt
  charts/aether/templates/_helpers.tpl
  charts/aether/templates/configmap.yaml
  charts/aether/templates/deployment.yaml
  charts/aether/templates/ingress.yaml
  charts/aether/templates/service.yaml
  charts/aether/templates/serviceaccount.yaml
  charts/aether/values.yaml
Labels: helm
